services:


  agorakit_php:
    container_name: agorakit_php
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ../../:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: :80
    tty: true
    networks:
      - agorakit


  agorakit_database:
    image: mariadb:latest
    container_name: agorakit_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agorakit
      MYSQL_USER: agorakit
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - agorakit

  agorakit_phpmyadmin:
    container_name: agorakit_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=agorakit_database
      - PMA_USER=root
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=1G
    networks:
          - agorakit
    depends_on:
      - agorakit_database
  
  
  agorakit_mailpit:
      container_name: agorakit_mailpit
      image: 'axllent/mailpit:latest'
      ports:
          - '${FORWARD_MAILPIT_PORT:-1025}:1025'
          - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
      networks:
          - agorakit

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
  database:


networks:
  agorakit:
    driver: bridge