services:
  agorakit_php:
    restart: always
    container_name: agorakit_prod
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ../../:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    networks:
      - agorakit


# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:


networks:
  agorakit:
    driver: bridge